package(
    default_visibility = ["//visibility:public"],
    licenses = ["notice"],
)

py_binary(
    name = "header_config",
    srcs = ["header_config.py"],
    visibility = ["//visibility:public"],
)
